# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2022.9.23.dev22+g2f6c477.d20230210'
__version_tuple__ = version_tuple = (2022, 9, 23, 'dev22', 'g2f6c477.d20230210')
