# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2022.9.23.dev20+g336cf24.d20230209'
__version_tuple__ = version_tuple = (2022, 9, 23, 'dev20', 'g336cf24.d20230209')
