# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2021a17.dev16+g0a3d52b1.d20230220'
__version_tuple__ = version_tuple = (2021, 'dev16', 'g0a3d52b1.d20230220')
